version: '3.8'

services:
  worker_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: media_downloader_backend
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - WORKER_MAX_CONCURRENCY=4
    volumes:
      - ./downloads:/app/downloads
      - ./src/backend:/app/src/backend
    restart: unless-stopped
